/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    PollinationStation: {
      address: "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "daoAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "title",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "socials",
              type: "string",
            },
          ],
          name: "DAOCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "needId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "dao",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "description",
              type: "string",
            },
          ],
          name: "NeedCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "pollinId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "daoWithNeed",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "daoWithOffering",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "needId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "descriptionOfRelationship",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "confidence",
              type: "uint256",
            },
          ],
          name: "PollinCreated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_title",
              type: "string",
            },
            {
              internalType: "string",
              name: "_description",
              type: "string",
            },
            {
              internalType: "string",
              name: "_socials",
              type: "string",
            },
          ],
          name: "addDAO",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_description",
              type: "string",
            },
          ],
          name: "addNeed",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_daoWithNeed",
              type: "address",
            },
            {
              internalType: "address",
              name: "_daoWithOffering",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_needId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_descriptionOfRelationship",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "_confidence",
              type: "uint256",
            },
          ],
          name: "addPollin",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "daos",
          outputs: [
            {
              internalType: "address",
              name: "daoAddress",
              type: "address",
            },
            {
              internalType: "string",
              name: "title",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "socials",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_daoAddress",
              type: "address",
            },
          ],
          name: "getDAO",
          outputs: [
            {
              internalType: "string",
              name: "title",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "socials",
              type: "string",
            },
            {
              internalType: "uint256[]",
              name: "needIds",
              type: "uint256[]",
            },
<<<<<<< HEAD
            {
              internalType: "uint256[]",
              name: "pollinIds",
              type: "uint256[]",
            },
=======
>>>>>>> web-app
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_needId",
              type: "uint256",
            },
          ],
          name: "getNeed",
          outputs: [
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "address",
              name: "dao",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_pollinId",
              type: "uint256",
            },
          ],
          name: "getPollin",
          outputs: [
            {
              internalType: "address",
              name: "daoWithNeed",
              type: "address",
            },
            {
              internalType: "address",
              name: "daoWithOffering",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "needId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "descriptionOfRelationship",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "confidence",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "needCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "needs",
          outputs: [
            {
              internalType: "uint256",
              name: "needId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "address",
              name: "dao",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pollinCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "pollins",
          outputs: [
            {
              internalType: "uint256",
              name: "pollinId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "daoWithNeed",
              type: "address",
            },
            {
              internalType: "address",
              name: "daoWithOffering",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "needId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "descriptionOfRelationship",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "confidence",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
